### ISSUE TITLE
Unable to fetch parameters from parameter store for this account

### ISSUE THREAD

**Issue by ayoubhamaoui** [aws-samples/amazon-deequ-glue#4]
I tried to deploy the template with steps that you mentioned in doc but I got this error
unable to fetch parameters (/DataQuality/S3/ArtifactsBucket) from parameter store for this account

I added this policy to user but still get same error :
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ssm:PutParameter",
                "ssm:DeleteParameter",
                "ssm:GetParameterHistory",
                "ssm:GetParametersByPath",
                "ssm:GetParameters",
                "ssm:GetParameter",
                "ssm:DeleteParameters",
                "ssm:AddTagsToResource"
            ],
            "Resource": "arn:aws:ssm:*:*:parameter/myparam/test/*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "ssm:DescribeParameters",
                "kms:ListAliases"
            ],
            "Resource": "*"
        }
    ]
}
```

**Comment by jaidisido** [comment]
It does seem that your user policy is missing some permissions. The SSM parameter is created right after the bucket and holds the name of the bucket under the /DataQuality/S3/ArtifactsBucket path in parameter store ([here](https://github.com/aws-samples/amazon-deequ-glue/blob/master/src/deploy.sh#L58)).

On the other hand in your policy, SSM actions are only allowed on this path: ```parameter/myparam/test/*```. 

You can either change it to:
```"Resource": "arn:aws:ssm:*:*:parameter/*"```
to cover all parameters. Or to:
```"Resource": "arn:aws:ssm:*:*:parameter/DataQuality/S3/ArtifactsBucket"```
to be specific and limit it to that exact path

Beyond this issue, you should make sure that your user policy is wide enough to cover all services used in this solution (IAM, Amplify... and many more). Otherwise you might face other permissions issues when deploying

**Comment by ayoubhamaoui** [comment]
yes it worked for me thank you
